mvn install:install-file -Dfile=gudusoft.gsqlparser.jar -DgroupId=gudusoft.gsqlparser -DartifactId=gsqlparser -Dversion=latest -Dpackaging=jar
mvn install:install-file -Dfile=greenplum_5.1.4.jar -DgroupId=com.greenplum -DartifactId=greenplum -Dversion=5.1.4 -Dpackaging=jar
mvn install:install-file -Dfile=mssql-jdbc-8.2.0.jre8.jar -DgroupId=com.mssql -DartifactId=mssql -Dversion=7.4 -Dpackaging=jar
mvn install:install-file -Dfile=snowflake-jdbc-3.12.9.jar -DgroupId=net.snowflake -DartifactId=snowflake -Dversion=3.12.9 -Dpackaging=jar
mvn install:install-file -Dfile=netezza-1.0.jar -DgroupId=org.netezza -DartifactId=netezza -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=ojdbc-1.1.1.jar -DgroupId=com -DartifactId=ojdbc -Dversion=1.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=RedshiftJDBC42-no-awssdk-1.2.53.1080.jar -DgroupId=RedshiftJDBC42 -DartifactId=RedshiftJDBC42 -Dversion=latest -Dpackaging=jar
mvn install:install-file -Dfile=terajdbc4.jar -DgroupId=com.terajdbc4 -DartifactId=terajdbc4 -Dversion=latest -Dpackaging=jar
mvn install:install-file -Dfile=tdgssconfig.jar -DgroupId=com.teraconfig4 -DartifactId=teraconfig4 -Dversion=latest -Dpackaging=jar
